title: "the CGCS"
description: "The missions hub of Southeastern Baptist Theological Seminary"
remote_theme: pmarsceill/just-the-docs
color_scheme: "pnd"
search_enabled: true
# Set a path/url to a logo that will be displayed instead of the title
logo:

# Footer Content
# Appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"