title: "The CGCS"
description: "The documentation site for the missions hub of Southeastern Baptist Theological Seminary"
remote_theme: just-the-docs/just-the-docs
color_scheme: "pnd"
search_enabled: true

# Set a path/url to a logo that will be displayed instead of the title
logo:


