title: "The CGCS"
description: "The documentation site for the missions hub of Southeastern Baptist Theological Seminary"
remote_theme: just-the-docs/just-the-docs
color_scheme: "pnd"
search_enabled: true

# Set a path/url to a logo that will be displayed instead of the title
logo:


# Aux links for the upper right navigation
aux_links:
  "The CGCS":
    - "//www.thecgcs.org"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# External navigation links
nav_external_links:
  - title: The CGCS
    url: https://www.thecgcs.org/

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2023 The CGCS."