title: "The CGCS"
description: "The documentation site for the missions hub of Southeastern Baptist Theological Seminary"
remote_theme: just-the-docs/just-the-docs
color_scheme: "pnd"
search_enabled: true

# Set a path/url to a logo that will be displayed instead of the title
logo:

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Aux links for the upper right navigation
aux_links:
  "CGCS Main Website":
    - "//www.thecgcs.org"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true