title: "the CGCS"
description: "The missions hub of Southeastern Baptist Theological Seminary"
remote_theme: pmarsceill/just-the-docs
color_scheme: "pnd"
search_enabled: true
# Set a path/url to a logo that will be displayed instead of the title
logo:
