title: "The CGCS"
description: "The documentation site for the missions hub of Southeastern Baptist Theological Seminary"
remote_theme: pmarsceill/just-the-docs
color_scheme: "pnd"
search_enabled: false

# Set a path/url to a logo that will be displayed instead of the title
logo:

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"